### ISSUE TITLE
Feature Request: Item name discovery

### ISSUE THREAD

**Issue by TheKrumpet** [TeamDman/SuperFactoryManager#107]
It can sometimes be pretty hard to work out what the script wants me to call an item (currently I just guess and check with wildcards, solving the item name as though it's a word puzzle). Some method of querying the mod for names would be ideal.

Possibly this takes the form of a slot in the factory manager, or a new block specifically for this purpose.

Nice to have would be the ability to copy the item name to the clipboard.

**Comment by TeamDman** [comment]
F3+h should show advanced tooltips

If you hold ctrl in the text editor it should underline some words, if you position your cursor over those words and hit ctrl+space it should bring up more context

Iif you do "input *ingot* from chest" when you should be able to see the names of all the items that matched the pattern, and the context for the chest or the input statement will have more info.

There's also the inspector you can open in any inventory by pressing ctrl+i which has a button to view the names of items in the chest; the network tool will show something similar when used on a block

Mostly a documentation problem since these features are hard to find out about when you don't know about them

**Comment by TheKrumpet** [comment]
Okay, I'll play around with these features and possibly submit a PR for the docs, because despite a lot of googling I couldn't find them anywhere.
