### ISSUE TITLE
Server time-out after using "each" term

### ISSUE THREAD

**Issue by ajlag3333** [TeamDman/SuperFactoryManager#132]
Server times out after every restart.
Crash report in the appendix.
[crash-2024-06-18_13.10.08-server.txt](https://github.com/user-attachments/files/15885755/crash-2024-06-18_13.10.08-server.txt)

**Comment by TeamDman** [comment]
ah crap yeah that's fixed in the latest update
`INPUT EACH *seed* FROM a`
expands to
`INPUT EACH item:*:*seed* FROM a`
which expands to every item in the game matching `*seed*`
...
you can guess what happens if the `*seed*` is omitted...

I'm trying to get the new build up very soon
sorry for the inconvenience, worst case maybe mcedit the offending manager away D:
I know forge has a way to remove erroring tile entities, but I don't know if removing lagging ones is a thing

**Comment by ajlag3333** [comment]
Thank you for your quick answer. I fixed the issue for my side deleting the factory manager via AmuletEditor. For now i will go on avoiding the term till it is fixed. But no problem, you don't need to rush, that's how it works for now. Have a great day :)

**Comment by TeamDman** [comment]
TIL amulet exists, glad you could fix it for now

**Comment by TeamDman** [comment]
addressed in latest build
