### ISSUE TITLE
missing item in input filter

### ISSUE THREAD

**Issue by LocalBoomer** [TeamDman/SuperFactoryManager#23]
I'm not sure if this is a bug or what but I cannot find solidified experience (from Actually Additions) in the Items whitelist.

MC 1.12.2
Actually Additions R140 (1.12.2)
SFM 2.0.9
Forge 14.23.4.2759

Edit 1: Seems I can't find anything from AA in the whitelist. Only buckets of AA fluids which I would assume are being registered differently?
Edit 2: Just restarted the pack after updating Refined Storage and RS Addons along with disabling Scannable and AA Items are showing up now. I have no idea why but I'm going to assume it was some weird one off bug. I'll necro this if it comes back again.

**Comment by TeamDman** [comment]
The way SFM searches items is it caches the entire item list when you join a world. The most likely cause of this issue is that the pack you're using has a large quantity of items, and the thread that was busy caching hadn't gotten to Actually Additions yet.
Two solutions (for me to think about): 
Cache the item list on load rather than on join (will slow down pack launch times)
or
Aggressively search if the cache isn't fully populated by the time the user is searching stuff (The old way, usually freezes the main thread, ugly)

**Comment by LocalBoomer** [comment]
470~ mods, so yeah a lot of items (:
