### ISSUE TITLE
Output bug with certain inventories

### ISSUE THREAD

**Issue by Zxirl** [TeamDman/SuperFactoryManager#28]
Mod v2.0.12 - FTB Interactions modpack

Attempting to output to a Cache (thermal expansion) or Barrel (Ender Utilties) works up 64 items and then stops attempting to move items, even though the mentioned storage blocks can contain 20,000 and 4096 items respectively.

**Comment by TeamDman** [comment]
Thanks for the feedback!
Some old logic was doing calculations to see how many items to insert, rather than just attempting the insertion and seeing what the inventory said was remainder. This fix should improve _interactions_ with other funky inventories as well.
New build on curseforge soon, it should also make it into the next Interactions update
