### ISSUE TITLE
Clusters Not Working With Double Sided & Transforming Camouflage

### ISSUE THREAD

**Issue by MRuth** [TeamDman/SuperFactoryManager#33]
It does not appear that you can add a Double Sided or a Transforming Camouflage block to a Cable or Advanced Cable Cluster.  The normal Camouflage Cable can be added though.

**Comment by TeamDman** [comment]
General note: I'm pretty sure that normal cable clusters originally couldn't have the double sided or advanced cables either.

The advanced cluster, however, should be able to.

Will look into it!, thanks!

**Comment by TeamDman** [comment]
I think I misremembered the cluster thing.
You could (and still can) use camouflages on normal clusters, however, only advanced clusters still function as cables. That's why people would always use advanced clusters with the camouflages, to hide/decorate their cables while maintaining functionality.
